
function initLevel()
{
  var level = new Array();
  
  level.push( "INSTRUCTIONS" );
  level.push( "These are the events that occurred in 2016. Most of these are headlines from NPR.org. (Implicit content warning for everything). Use your spaceship to choose which events get to stay and which have to go by shooting them. A and D to move, J to shoot." );
  
  level.push( "Fork this repository to add to the event list. github.com/RachelJMorris/2016-in-Review" );
  
  level.push( "January 3 - Armed Group Takes Over Federal Building Following Protest In Oregon" );
  level.push( "January 4 - 400 Years After His Death, Shakespeare's First Folio Goes Out On Tour" );
  level.push( "January 5 - 'A Bit Of A Montessori 2.0': Khan Academy Opens A Lab School" );
  level.push( "January 6 - Texas Trooper Who Arrested Sandra Bland Indicted And Told He'll Be Fired" );
  level.push( "January 7 - Monkey Can't Own Copyright To His Selfie, Federal Judge Says" );
  level.push( "January 9 - After Second Escape, Mexican Drug Kingpin 'El Chapo' Recaptured" );
  level.push( "January 10 - David Bowie dies" );
  level.push( "January 10 - Doctors Without Borders Says Hospital Was Hit In Yemen" );
  level.push( "January 12 - Explosion In Heart Of Istanbul's Tourist Area Kills At Least 10" );
  level.push( "January 13 - Responding To Nuclear Test, S. Korea Cranks Up The K-Pop" );
  level.push( "January 14 - West Africa Is Finally Declared Ebola-Free — For Now" );
  level.push( "January 14 - Alan Rickman dies" );
  level.push( "January 14 - Goldman Sachs Will Pay $5 Billion To Settle Financial-Crisis Claims" );
  level.push( "January 15 – Taiwan Now Has A Giant, Shiny, Shoe-Shaped Church" );
  level.push( "January 16 – Obama Declares State Of Emergency Over Flint's Contaminated Water" );
  level.push( "January 16 – Implementation Day Arrives: Sanctions On Iran Are Lifted" );
  level.push( "January 16 – The International Atomic Energy Agency announces that Iran has adequately dismantled its nuclear weapons program allowing the United Nations to lift sanctions immediately." );
  level.push( "January 23 - Former Defense Secretary Donald Rumsfeld Tries His Hand At App Development - A new app based on Winston Churchill's tweak on Solitaire was designed with the help of Donald Rumsfeld." );
  level.push( "January 23 - China Blames Goats For 2015 Drop In Birth Rate" );
  level.push( "January 24 - Four Killed In Canada School Shooting" );
  level.push( "January 25 - PEN American Center Awards Free-Speech Prize To J.K. Rowling" );
  level.push( "January 26 - Abe Vigoda dies" );
  level.push( "January 27 – Shooting At Homeless Camp In Seattle Kills 2, Wounds 3" );
  level.push( "January 28 – The World Health Organization announces an outbreak of the Zika virus." );
  level.push( "January 28 – 4 Militants Remain In Oregon Wildlife Refuge, As FBI Negotiations Go On" );
  level.push( "January 29 – 'Affluenza Teen' To Remain In Juvenile Detention For Now" );
  level.push( "January 30 – Boat Sinks En Route To Greece, Killing At Least 37 Migrants" );
  
  level.push( "February 2 – Teens Arrested In Mass Shooting At Seattle Homeless Camp" );
  level.push( "February 2 – Encryption May Hurt Surveillance, But Internet Of Things Could Open New Doors" );
  level.push( "February 2 – Yahoo Laying Off Staff And Considering Selling Itself" );
  level.push( "February 2 – Obama Asks Congress For More Money To Fight Opioid Drug Abuse" );
  level.push( "February 3 – Cosby Sexual Assault Case Is Cleared To Proceed" );
  level.push( "February 4 – Martin Shkreli Takes The Fifth, But Can't Resist Firing Back" );
  level.push( "February 4 – With Oil Prices Languishing, Shell Reports 80 Percent Drop In Earnings" );
  level.push( "February 5 – Dave Mirra dies" );
  level.push( "February 5 – At Least 14 Dead After Earthquake Hits Southern Taiwan" );
  level.push( "February 7 – Super Bowl 50: Denver Broncos Take Home The NFL Title" );
  level.push( "February 7 – North Korea launches a long-range rocket into space ); violating multiple UN treaties and prompting condemnation from around the world." );
  level.push( "February 8 – UNICEF Estimate Of Female Genital Mutilation Up By 70 Million" );
  level.push( "February 10 – Bernie Sanders Dines With Al Sharpton In Harlem" );
  level.push( "February 11 – Oregon Occupation Ends As Last Holdout Surrenders" );
  level.push( "February 11 – Morgan Stanley Will Pay $3.2 Billion For Contributing To Mortgage Crisis" );
  level.push( "February 12 – Antonin Scalia dies" );
  level.push( "February 13 – Over 1,000 Clinton Documents Released, Including 84 New Classified Emails" );
  level.push( "February 15 – Airstrikes Hit 2 Hospitals In Syria, Killing At Least 50" );
  level.push( "February 17 – Apple Opposes Judge's Order To Help FBI Unlock San Bernardino Shooter's Phone" );
  level.push( "February 17 – Dozens Of People Killed In Blast Near Turkish Military Buildings" );
  level.push( "February 18 – Pope Says Trump 'Is Not Christian'" );
  level.push( "February 19 – Harper Lee dies" );
  level.push( "February 20 – Jeb Bush Ends His Presidential Campaign" );
  level.push( "February 22 – Nearly 2 Dozen People Dead After Tropical Cyclone Hits Fiji" );
  level.push( "February 24 – Plane Crash In Nepal Kills All 23 Aboard" );
  level.push( "February 29 – Advertising Company Will Use Its Billboards To Track Passing Cellphones" );
  
  level.push( "March 1 – Astronauts Back Home After A Year In Space" );
  level.push( "March 5 – Scientists Discover 'Remarkable Little Octopod,' Possibly New Species" );
  level.push( "March 6 – Nancy Reagan dies" );
  level.push( "March 9 – After Equipment Woes, NASA Mission To Mars Is Rescheduled For 2018" );
  level.push( "March 9 – George Martin dies" );
  level.push( "March 14 – The ESA and Roscosmos launch the joint ExoMars Trace Gas Orbiter on a mission to Mars." );
  level.push( "March 14 – After Bombing In Ankara, Turkey Hits Kurdish Targets In Northern Iraq" );
  level.push( "March 21 – Obama And Castro Share An Awkward Handshake In Cuba After Historic Meeting" );
  level.push( "March 22 – Bubble Tea Is Back — With A Vengeance" );
  level.push( "March 22 – Three coordinated bombings in Brussels Belgium kill at least 32 and injure at least 250." );
  level.push( "March 27 – A suicide blast in Gulshan-e-Iqbal Park Lahore kills 75 people and injures around 340 others" );
  level.push( "March 27 – Internet Trolls Turn A Computer Into A Nazi" );
  level.push( "March 27 – Explosion At Park In Lahore, Pakistan, Kills At Least 70" );
  level.push( "March 28 – The FBI Has Successfully Unlocked The iPhone Without Apple's Help" );
  level.push( "March 29 – EgyptAir Plane Hijacked While Flying To Cairo" );
  level.push( "March 31 – DraftKings And FanDuel To Suspend Contests On College Sports 'Indefinitely'" );
  level.push( "March 31 – Overpass Collapse In Kolkata, India, Kills More Than A Dozen People" );
  
  level.push( "April 2 – Clashes between Armenian and Azerbaijani military in Nagorno-Karabakh kill at least 193 people which becomes the heaviest breach of the 1994 ceasefire." );
  level.push( "April 3 – The International Consortium of Investigative Journalists (ICIJ) and the German newspaper Süddeutsche Zeitung publishes a set of 11.5 million confidential documents from the Panamanian corporate Mossack Fonseca that provides detailed information on more than 214,000 offshore companies including the identities of shareholders and directors including noted personalities and heads of state." );
  level.push( "April 4 – Dog Leads Police On Chase Across San Francisco Bridge" );
  level.push( "April 6 – Merle Haggard dies" );
  level.push( "April 6 – Judge Dismisses Kesha's Hate-Crime Claims Against Producer Dr. Luke" );
  level.push( "April 8 – SpaceX Rocket Lands Safely On A Ship At Sea For the First Time" );
  level.push( "April 10 - Kerala, India: At Least 100 Killed In Temple Fires" );
  level.push( "April 11 - Al-Jazeera America Prepares Farewell Broadcast" );
  level.push( "April 11 - Number Of Wild Tigers Increases For First Time In 100 Years" );
  level.push( "April 12 - Pope Francis Replaces Ambassador Who Arranged Kim Davis Meeting" );
  level.push( "April 13 - Voice Of Lucky Charms Leprechaun, Arthur Anderson, Dies At 93" );
  level.push( "April 13 - Technology Helps A Paralyzed Man Transform Thought Into Movement" );
  level.push( "April 14 - Video Shows Some Schoolgirls Kidnapped By Boko Haram Still Alive" );
  level.push( "April 14 - Sandy Hook Families' Lawsuit Against Gun Companies Can Move Forward, Judge Says" );
  level.push( "April 16 - Powerful Earthquake Hits Ecuador's Coast, Killing At Least 262" );
  level.push( "April 17 - South Sudanese Gunmen Kill At Least 140 Civilians In Ethiopia, Government Says" );
  level.push( "April 18 - Bus Explosion, Fire In Jerusalem Injures At Least 16" );
  level.push( "April 18 - Hundreds Dead, Thousands Homeless After Quake In Ecuador" );
  level.push( "April 20 - Up In Flames: Kenya Burns More Than 100 Tons Of Ivory" );
  level.push( "April 20 - Treasury Decides To Put Harriet Tubman On $20 Bill" );
  level.push( "April 20 - Utah Declares Porn A Public Health Hazard" );
  level.push( "April 21 - Prince dies" );
  level.push( "April 22 - Carnival Says Its Cruises To Cuba Can Now Include Cuban-Born Passengers" );
  level.push( "April 22 - Uber Settles 2 Lawsuits, Won't Have To Treat Drivers As Employees" );
  level.push( "April 23 - Beyoncé's album Lemonade released" );
  level.push( "April 24 - 'Islamic Fashion' Causes A Stir In France" );
  level.push( "April 25 - Petition Calls For Boycott Of Target's 'Inclusive' Bathroom Policy" );
  level.push( "April 26 - India Will Require 'Panic Button' On Cellphones To Report Assault" );
  level.push( "April 26 - Editor Of Bangladesh's Only LGBT Magazine Is Hacked To Death" );
  level.push( "April 27 - Former House Speaker Dennis Hastert Admits To Sexual Abuse" );
  level.push( "April 28 - Boehner Says He's Never 'Worked With A More Miserable Son Of A Bitch' Than Cruz" );
  level.push( "April 28 - Hospital In Aleppo 'Fully Destroyed' In Airstrike, Red Cross Says" );
  level.push( "April 29 - Lawsuit Will Decide Who Owns 'Star Trek' Language Klingon" );
  level.push( "April 29 - Key And Peele Duo Are Back As Action-Duo In 'Keanu'" );
  level.push( "April 29 - Comcast Buys DreamWorks Animation For $3.8 Billion In Race Against Disney" );
  
  level.push( "May 11 – Suicide Bombings In Baghdad Kill More Than 85 People" );
  level.push( "May 12 – George Zimmerman Auctioning Off Gun He Used To Kill Trayvon Martin" );
  level.push( "May 15 – Library Of Congress Opens 'Jazz Singers' Exhibition" );
  level.push( "May 17 – After 50-Year Legal Struggle, Mississippi School District Ordered To Desegregate" );
  level.push( "May 19 – EgyptAir Flight 804 crashes with 66 people on board over the Mediterranean en route from Paris to Cairo." );
  level.push( "May 20 – 'I Will Never Let You Down,' Trump Tells National Rifle Association" );
  level.push( "May 20 – Super Hot! India Records Its Highest Temperature Ever" );
  level.push( "May 27 – Obama Makes Historic Visit To Hiroshima Memorial Peace Park" );
  level.push( "May 30 – 3 Shipwrecks In 3 Days: 700 People Die Trying To Cross Mediterranean" );
  
  level.push( "June 3 - Muhammad Ali dies" );
  level.push( "June 12 – 50 Dead, 53 Hospitalized In Orlando Shooting" );
  level.push( "June 12 – Donors Line Up To Give Blood In Florida" );
  level.push( "June 13 – Microsoft To Buy LinkedIn For $26.2 Billion, Pursuing 'Productivity' Industry" );
  level.push( "June 15 – In Defense Bill, Senate Approves Plan For Women To Register For Draft" );
  level.push( "June 17 – Neither Male Nor Female: Oregon Resident Legally Recognized As Third Gender" );
  level.push( "June 19 – Colorado Mother Fights Off Mountain Lion To Save Her Son" );
  level.push( "June 22 – Demanding Action On Gun Control, House Democrats Stage Sit-In" );
  level.push( "June 23 – The United Kingdom votes in a referendum to leave the European Union." );
  level.push( "June 26 – Obama Declares Major Disaster In West Virginia After Historic Flooding" );
  level.push( "June 28 – ISIL claims responsibility for attacking Atatürk Airport in Istanbul killing 45 and injuring around 230." );
  level.push( "June 30 – 1.4 Million Adults Identify As Transgender In America, Study Says" );
  level.push( "June 30 – Pentagon Says Transgender Troops Can Now Serve Openly" );
  level.push( "June 30 – Boris Johnson Says He Won't Run For Prime Minister" );
  
  level.push( "July 4 – NASA's Juno spacecraft enters orbit around Jupiter and begins a 20-month survey of the planet." );
  level.push( "July 14 – Bodycam Video Shows Police Shooting Of Unarmed 19-Year-Old In Fresno" );
  level.push( "July 15 – 'Sheer Terror' As Attack Along French Riviera Kills At Least 84" );
  level.push( "July 19 – Section Of Melania Trump's Monday Speech Mirrors Michelle Obama's In 2008" );
  level.push( "July 19 – Trump Campaign Says Melania Trump's Words Were Her Own" );
  level.push( "July 22 – 'Heat Dome' Causing Excessive Temperatures In Much Of U.S." );
  level.push( "July 22 – The final videocassette recorder is manufactured by the Japanese company Funai." );
  level.push( "July 23 – Leaked Democratic Party Emails Show Members Tried To Undercut Sanders" );
  level.push( "July 24 – 2 Major California Wildfires Prompt Thousands Of Home Evacuations" );
  level.push( "July 24 – Debbie Wasserman Schultz To Step Down As Democratic Chair After Convention" );
  level.push( "July 24 – International Olympic Committee Decides Not To Ban Russian Team" );
  level.push( "July 26 – Solar-Powered Plane Completes Historic Circumnavigation" );
  level.push( "July 26 – Black Lives Matter Activists Lead March To Democratic Convention" );
  level.push( "July 26 – Hillary Clinton Makes History As She Secures Presidential Nomination" );
  level.push( "July 26 – Solar Impulse 2 becomes the first solar-powered aircraft to circumnavigate the Earth." );
  level.push( "July 26 – Miss Cleo dies" );
  level.push( "July 26 – 19 Die In Knife Attack At Care Facility West Of Tokyo" );
  level.push( "July 27 – Tortoise Wins Again: Slow And Steady Pace Outruns L.A. Fire" );
  level.push( "July 29 – New Reports Of Hackers In Democratic Party Computer Systems" );
  level.push( "July 30 – Skydiver Luke Aikins Sets Record For Highest Jump Without Parachute" );
  level.push( "July 31 – Tokyo Elects Its First Female Governor" );
  
  level.push( "August 12 - Louisiana Governor Declares State Of Emergency As Floodwaters Rise" );
  level.push( "August 5–21 – The 2016 Summer Olympics are held in Rio de Janeiro Brazil." );
  level.push( "August 18 – Usain Bolt Wins Eighth Olympic Gold Medal In The 200m Sprint" );
  level.push( "August 20 – 'Googly-Eyed' Stubby Squid Captures Internet's Attention" );
  level.push( "August 21 – At Least 50 Killed, 90 Wounded In Turkey Wedding Bombing" );
  level.push( "August 24 – Canada's Mounties Say Female Officers Can Wear Hijabs" );
  level.push( "August 25 – WhatsApp Will Start Sharing Data, Including Phone Numbers, With Facebook" );
  level.push( "August 27 – 49ers Quarterback Sits Out National Anthem To Protest Oppression Of Minorities" );
  level.push( "August 28 – 4 Years After Tragedy, A New Sandy Hook Elementary Prepares To Open Its Doors" );
  level.push( "August 29 – Gene Wilder dies" );
  level.push( "August 29 – 'Mars Mission' Crew Emerges From Yearlong Simulation In Hawaii" );
  level.push( "August 29 – Suicide Bombing In Yemen Kills At Least 54; Attack Claimed By Islamic State" );
  level.push( "August 31 – The Brazilian Senate votes (61–20) to impeach the President of Brazil Dilma Rousseff." );
  
  
  level.push( "September 3 – The US and China ); together responsible for 40% of the world's carbon emissions both ratify the Paris global climate agreement." );
  level.push( "September 8 – NASA launches OSIRIS-REx ); its first asteroid sample return mission. The probe will visit Bennu and is expected to return with samples in 2023." );
  level.push( "September 9 – The government of North Korea conducts its fifth and reportedly biggest nuclear test. World leaders condemn the act with the South calling it \"maniacal recklessness\"." );
  level.push( "September 15 – Teen Creates App So Bullied Kids Never Have To Eat Alone" );
  level.push( "September 18 – After Switching To Judo, Blind U.S. Paralympian Wins Bronze In Rio" );
  level.push( "September 21 – N.C. Protesters Close Section Of I-85 After Police-Involved Shooting" );
  level.push( "September 22 – Yahoo Reveals Massive Data Breach; Internet Fixates On Fantasy Football" );
  level.push( "September 23 – Syria's Famed 'White Helmets' Group Says It's Being Targeted In New Offensive" );
  level.push( "September 27 – 92 Percent Of The World's Population Breathes Substandard Air, WHO Says" );
  level.push( "September 27 – U.S. Government To Pay $492 Million To 17 American Indian Tribes" );
  level.push( "September 27 – Elon Musk Unveils His Plan For Colonizing Mars" );
  level.push( "September 28 – International investigators conclude that Malaysia Airlines Flight 17 was shot down by a Buk missile that came from an area controlled by pro-Russian rebels." );
  level.push( "September 28 – Global CO2 levels exceed 400 ppm at the time of year normally associated with minimum levels. A 400 ppm level is believed to be higher than anything experienced in human history." );
  level.push( "September 29 – 'Cup Noodles' Turns 45" );
 
  level.push( "October 22 - AT&T Reaches Deal To Buy Time Warner For More Than $85 Billion" );
  level.push( "October 24 - Adnan Syed, Subject Of 'Serial,' Asks To Be Released On Bail" );
  level.push( "October 25 - Campus Cop On Trial For Shooting Death During Routine Traffic Stop" );
  level.push( "October 25 - Amusement Park Accident In Australia Kills 4" );
  level.push( "October 25 - Antarctica's Ice Sheets Are Melting Faster — And From Beneath" );
  level.push( "October 25 - Attempting To Woo Latino Voters, Marco Rubio Gets Booed At Orlando Festival" );
  level.push( "October 27 - Leaders Of Oregon Wildlife Refuge Standoff Acquitted" );
  level.push( "October 27 - Dozens Dead In What UNICEF Calls One Of Worst School Bombings In Syria's War" );
  level.push( "October 27 - Researchers Say They've Found A Bit Of Fossilized Dinosaur Brain" );
  level.push( "October 27 - Obama Urges A Boost In IT Spending To Secure Federal Computers" );
  level.push( "October 28 - Tensions Escalate As Police Clear Protesters Near Dakota Access Pipeline" );
  level.push( "October 28 - Supreme Court Will Hear Case On Bathroom Rules For Transgender Students" );
  level.push( "October 29 - After Nearly 2 Decades, Californians Revisit Ban On Bilingual Education" );
  level.push( "October 29 - FBI Head Under Fire For Clinton Email Scrutiny Days Before Election" );
  level.push( "October 30 - NASA's New 'Intruder Alert' System Spots An Incoming Asteroid" );
  level.push( "October 30 - 6.6-Magnitude Earthquake Flattens Much Of Historic Basilica In Central Italy" );
  level.push( "October 30 - Women Win 30 Seats In Iceland's Parliament — More Than Any Party" );
  
  level.push( "November 1 - 33 Miners Reported Dead After Blast In China" ); 
  level.push( "November 2 - For First Time, Glamour's Women Of The Year Include A Man: Bono" ); 
  level.push( "November 2 - Chicago Cubs Defeat Cleveland Indians In 10 Innings To Win World Series" ); 
  level.push( "November 2 - Hulk Hogan Reaches Settlement With Gawker Worth Over $31 Million" ); 
  level.push( "November 2 - Neiman Marcus Is Selling Frozen Collard Greens For $66 Plus Shipping" ); // adding dumb stuff just because
  level.push( "November 3 - Protesters, Police Still Clashing Over Disputed North Dakota Pipeline" );
  level.push( "November 3 - Steven Seagal Is Now A Citizen Of Russia, Courtesy Of Putin" );
  level.push( "November 3 - Male Birth Control Study Killed After Men Report Side Effects" );
  level.push( "November 3 - Is Nutella A Dessert Topping Or A Spread? The FDA Wants To Know" );
  level.push( "November 4 - Car Bomb Kills 8 In Turkey After Pro-Kurdish Legislators Detained For Questioning" );
  level.push( "November 4 - Middle School Suicides Reach An All-Time High" );
  level.push( "November 5 - Egypt's All-Woman Roller Derby Team Is Skating Past Stereotypes" );
  level.push( "November 6 - Gaza's Surfer Girl Hangs Up Her Board — And Not By Choice" );
  level.push( "November 7 - Janet Reno dies" );
  level.push( "November 7 - Australian Police Find Baby Koala In A Backpack" );
  level.push( "November 7 - Leonard Cohen dies" );
  level.push( "November 8 - At Susan B. Anthony's Grave, Visiting Hours Extended For Election Day Crowds" );
  level.push( "November 9 - For First Time, Openly LGBT Governor Elected: Oregon's Kate Brown" );
  level.push( "November 9 - In Ballot Measures, Pot Legalization Makes Strides" );
  level.push( "November 9 - Hillary Clinton Concedes Presidential Race To Donald Trump" );
  level.push( "November 9 - Monkeys Regain Control Of Paralyzed Legs With Help Of An Implant" );
  level.push( "November 9 - Woman In Iconic 'Afghan Girl' Photo Deported Back To Afghanistan" );
  level.push( "November 9 - Kamala Harris, Catherine Cortez Masto and Rep. Tammy Duckworth made historic inroads on Election Day, becoming, respectively, the first biracial woman in the Senate, the first Latina senator, and the first Thailand-born senator." );
  level.push( "November 10 - Somali Refugee Makes History In U.S. Election" );
  level.push( "November 10 - Medieval Leprosy Lurks In British Squirrels" );
  level.push( "November 10 - German Consulate In Northern Afghanistan Attacked" );
  level.push( "November 11 - Women Rush To Get Long-Acting Birth Control After Trump Wins" );
  level.push( "November 11 - Indian Currency Ban Sends Country Into Panic" );
  level.push( "November 11 - Zuckerberg Denies Fake News On Facebook Had Impact On The Election" );
  level.push( "November 13 - Threats And Intimidation Against Minorities Reported Nationwide" );
  level.push( "November 14 - Brendan Dassey Of 'Making A Murderer' Ordered Released From Prison" );
  level.push( "November 14 - 'The Worst I've Ever Seen'; Fires Sweep Through Southeastern U.S." );
  level.push( "November 14 - Gwen Ifill dies" );
  level.push( "November 15 - After Rocky Pause, Airstrikes Resume On Syria's Aleppo" );
  level.push( "November 15 - Tinder Now Lets Users Identify As Genders Other Than Male Or Female" );
  level.push( "November 16 - Minn. Police Officer Who Killed Philando Castile Is Charged With Manslaughter" );
  level.push( "November 17 - Mannequin Challenge Makes It To India, Nepal, Nigeria" );
  level.push( "November 19 - Trump Agrees To Settle Trump University Lawsuits For $25 Million" );
  level.push( "November 19 - 'Hamilton' Cast Makes Appeal To Attendee Mike Pence, Amid Emotional Audience" );
  level.push( "November 19 - Water Crisis Continues In Flint After Judge Orders Water Delivery" );
  level.push( "November 20 - At Least 133 Killed In Northern India Train Derailment" );
  level.push( "November 20 - At 56, Peggy Whitson Becomes Oldest Female Astronaut" );
  level.push( "November 22 - At Least 5 Children Die In Tennessee School Bus Crash" );
  level.push( "November 23 - Woman Injured At Standing Rock Protest Might Lose Arm, Family Says" );
  level.push( "November 25 - Florence Henderson dies" );
  level.push( "November 25 - Clinton's Popular-Vote Lead Is Now Over 2 Million" );
  level.push( "November 26 - Haiti Still Reels From Hurricane Matthew, One Month On" );
  level.push( "November 26 - Ron Glass, Emmy-Nominated Actor Best Known For 'Barney Miller,' Has Died At 71" );
  level.push( "November 28 - The Last Hospital In Eastern Aleppo Is No More" );
  level.push( "November 29 - Plane Carrying Brazilian Soccer Players Crashes In Colombia, Killing 71" );
  level.push( "November 29 - The Beauty Pageant Contestant Wore A Burkini" );
  level.push( "November 30 - Pelosi Overcomes Challenge To Win Re-Election As House Democratic Leader" );
  level.push( "November 30 - N.C. Officer Will Not Be Charged In Shooting Death Of Keith Lamont Scott" );
  
  
  level.push( "December 2 - Fidel Castro dies" );
  level.push( "December 2 - Unemployment Rate Drops To 4.6 Percent, Lowest Level Since 2007" );
  level.push( "December 3 - Yemen Crisis: Humanitarians Need 'Unconditional Access' To Reach The Food-Insecure" );
  level.push( "December 5 - The Death Toll In Oakland's Deadliest Fire Stands At 33" );
  level.push( "December 5 - The Army Corps of Engineers announced yesterday it will not approve a building permit for the key and final section of the Dakota Access pipeline." );
  level.push( "December 7 - 'Frantic' Search For Survivors After Earthquake In Indonesia Kills Nearly 100" );
  level.push( "December 8 - John Glenn dies" );
  level.push( "December 8 - Baby Dinosaur's 99 Million-Year-Old Tail, Encased In Amber, Surfaces In Myanmar" );
  level.push( "December 9 - South Korea Impeaches President" );
  level.push( "December 9 - Trump Transition Asks Energy Dept. Which Employees Work On Climate Change" );
  level.push( "December 10 - CIA Concludes Russian Interference Aimed To Elect Trump" );
  level.push( "December 10 - Explosions Rock Istanbul Soccer Stadium, Killing 38, Wounding 155" );
  level.push( "December 11 - Bomb Hits Coptic Christian Church In Cairo, Killing At Least 25" );
  level.push( "December 13 - Ohio Gov. Kasich Signs 20-Week Abortion Limit, Rejects 'Heartbeat Bill'" );
  level.push( "December 14 - Obama Administration Moves To Protect Planned Parenthood's Federal Funding" );
  level.push( "December 17 - Henry Heimlich dies" );
  level.push( "December 18 - Toddler Dies After Road-Rage Gunfire Hits Car ); Little Rock Police Say" );
  level.push( "December 18 - At Least 10 Die In Shootout At Crusader Castle In Jordan" );
  level.push( "December 18 - 19 - Evaculations in East Aleppo" );
  level.push( "December 19 - Truck driven into Berlin Christmas Market killing 12." );
  level.push( "December 19 - Calif. Judge Cleared Of Misconduct After Sentence In Stanford Sexual Assault Case" );
  level.push( "December 19 - The U.S. Electoral College votes for Donald Trump as president." );
  level.push( "December 19 - Russia's Ambassador to Turkey shot and killed in Ankara" );
    
  
  level.push( "SOURCES" );
  level.push( "https://en.wikipedia.org/wiki/2016" );
  level.push( "http://www.nytimes.com/interactive/projects/notable-deaths/2016" );
  level.push( "http://www.npr.org/" );
  level.push( "" );
  
  level.push( "PROGRAMMING AND ART BY" );
  level.push( "Rachel J Morris" );
  
  level.push( "MUSIC - Cyborg Ninja - FROM" );
  level.push( "Kevin MacLeod - http://incompetech.com/" );
  
  level.push( "SOUND EFFECTS GENERATED WITH" );
  level.push( "BFXR - http://incompetech.com/" );  
  
  level.push( "YEAR OVER" );  
  
  return level;
}

